version: 2

builds:
  - id: gt
    dir: .
    main: .
    binary: gt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

release:
  name_template: '{{ .Tag }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  format: "{{ .Message }}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
